services:
  stock-db:
    image: pgvector/pgvector:pg16
    container_name: stock-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "stockdb" 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
